[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#dfaf87"
yellow = "#d79921"

[colors.primary]
background = "#0E1018"
foreground = "#ebdbb2"

[env]
TERM = "xterm-256color"

[font]
size = 16.75

[font.bold]
family = "MesloLGMDZ Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGMDZ Nerd Font"
style = "Bold Italic"

[font.normal]
family = "MesloLGMDZ Nerd Font"
style = "Bold"

[scrolling]
history = 10000
multiplier = 3

[keyboard]
